name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Set Version
        run: npm --no-git-tag-version version 0.1.${{ github.run_number }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm ci

      - name: Test
        run: npm test

      - name: Production Build
        run: npm run build

      - name: Package
        run: npm pack

      - name: Authenticate with NPM registry
        if: github.ref == 'refs/heads/master'
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Publish NPM package
        if: github.ref == 'refs/heads/master'
        run: npm publish --access public
