name: Build

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
          package-manager-cache: false

      - run: npm --no-git-tag-version version 2.0.${{ github.run_number }}

      - run: npm ci

      - run: npm test

      - run: npm run build

      - if: github.ref == 'refs/heads/main'
        run: npm publish --access public
